run:
  timeout: 5m

linters:
  enable:
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - unused        # Finds unused variables, functions, types
    - bodyclose     # Ensures HTTP response bodies are closed
    - copyloopvar   # Checks loop variable captures in closures
    - errorlint     # Detects common error-handling issues
    - nilerr        # Finds `return err, nil` situations
    - rowserrcheck  # Ensures `Rows.Err()` is checked
    - sqlclosecheck # Ensures `Rows.Close()` is called
    - whitespace    # Detects trailing/leading whitespace

  disable:
    - staticcheck   # Temporarily disabled, can be re-enabled later

issues:
  exclude-rules:
    - path: _test\.go
      text: ".*"

  max-issues-per-linter: 0
  max-same-issues: 0