name: Integration Tests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  call-reusable-setup:
    uses: ./.github/workflows/setup.yml

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: call-reusable-setup
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: workspace-${{ github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run integration tests
        run: go test -v -timeout=10m -tags=integration ./raft -run=TestRaftIntegration