name: Lint
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  call-reusable-setup:
    uses: ./.github/workflows/setup.yml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: call-reusable-setup
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: workspace-${{ github.sha }}
          path: .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m
          working-directory: .
          skip-cache: true