name: Setup
on:
  workflow_call:

jobs:
  setup:
    name: Setup & Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate protobuf files
        run: |
          protoc --proto_path=. \
                 --go_out=. --go_opt=paths=source_relative \
                 --go-grpc_out=. --go-grpc_opt=paths=source_relative \
                 $(find . -name '*.proto')

      - name: Tidy dependencies after codegen
        run: go mod tidy

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v4
        with:
          name: workspace-${{ github.sha }}
          path: .
          retention-days: 1