name: Test Storage

on:
  push:
    branches: [main]
    paths:
        - 'storage/**'
  pull_request:
    paths:
        - 'storage/**'
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # For accurate diff on PRs
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      
      - name: Verify dependencies
        run: go mod verify
      
      # - name: Run linting
      #   uses: golangci/golangci-lint-action@v4
      #   with:
      #     version: latest
      #     args: |
      #       --timeout=5m
      #       --out-format=colored-line-number
      #       --exclude-dirs=proto
      
      - name: Run storage tests with coverage
        run: |
            # Run tests specifically for the ./storage package
            go test -v ./storage -race -coverprofile=storage-coverage.out -covermode=atomic | tee storage-test-output.txt
        
      - name: ✅ Show storage test results and coverage %
        run: |
          echo "### ✅ Storage Test Results:"
          grep -E '^(=== RUN|--- (PASS|FAIL))' storage-test-output.txt \
            | sed -E 's/=== RUN +/Running: /; s/--- PASS: /✅ Passed: /; s/--- FAIL: /❌ Failed: /'

          echo ""
          echo "### 📊 Storage Total Coverage:"
          # Use the storage-specific coverage file
          go tool cover -func=storage-coverage.out | grep total

      - name: Generate storage coverage report
        run: go tool cover -html=storage-coverage.out -o storage-coverage.html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: storage-coverage-report
          path: storage-coverage.html
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: storage-coverage.out
          flags: storage-unittests
          name: codecov-storage-${{ matrix.go-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
