name: Unit Tests

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - proto/**
  pull_request:
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # For accurate diff on PRs
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      
      - name: Verify dependencies
        run: go mod verify

      - name: Install protoc and Go plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Generate protobuf files
        run: |
          echo "Generating protobuf files for ./proto/*.proto and ./raft/proto/*.proto"
          protoc \
            --proto_path=. \
            --go_out=paths=source_relative:. \
            --go-grpc_out=paths=source_relative:. \
            $(find . -name '*.proto')

          echo "Protobuf generation complete."

      - name: Tidy dependencies
        run: go mod tidy # Ensures go.mod and go.sum are consistent
      
      
      # - name: Run linting
      #   uses: golangci/golangci-lint-action@v4
      #   with:
      #     version: latest
      #     args: |
      #       --timeout=5m
      #       --out-format=colored-line-number
      #       --exclude-dirs=proto
      
      - name: Run tests with coverage (entire repo, excluding .pb.go)
        run: |
          go test -v ./... -race -coverprofile=coverage.tmp.out -covermode=atomic | tee test-output.txt
          # Remove lines with *.pb.go and testutil/ from coverage report
          grep -vE '\.pb\.go:|(^|/)testutil/' coverage.tmp.out > coverage.out
          
        
      - name: ✅ Show test results and coverage %
        run: |
          echo "### ✅ Test Results:"
          grep -E '^(=== RUN|--- (PASS|FAIL))' test-output.txt \
            | sed -E 's/=== RUN +/Running: /; s/--- PASS: /✅ Passed: /; s/--- FAIL: /❌ Failed: /' \
            || echo "No test results found in output."

          echo ""
          echo "### 📊 Total Coverage:"
          go tool cover -func=coverage.out | grep total \
            || echo "Coverage data not found or 'total' line missing."

      - name: Generate coverage report
        if: success() || failure()
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report as artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.go-version }}
          path: coverage.html
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          flags: unittests
          name: codecov-${{ matrix.go-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true