name: Unit Tests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  call-reusable-setup:
    uses: ./.github/workflows/setup.yml

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    needs: call-reusable-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: workspace-${{ github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run tests and generate coverage
        run: |
          go test -v -timeout=5m ./... -coverprofile=coverage.tmp.out -covermode=atomic
          grep -vE '\.pb\.go:|/testutil/|/examples/' coverage.tmp.out > coverage.out
      
      - name: Debug coverage file
        run: |
          echo "Top of coverage.out:"
          head -n 10 coverage.out
          echo "Total lines:"
          wc -l coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unittests
          fail_ci_if_error: true
          verbose: true